a = ('b', 'c', 'd', 'e', 60, 25.48)
print(a +('r', 'rt', 300))
print(a*4)
print(a[3])
print(type(a))
print(id(a))

tuple =('alt', 'del', 'will', 125)
print(tuple)
tinytuple =(123, 'will')
print(tinytuple)
print(tuple+tinytuple)
print(tuple[0])
print(tuple[2:])
print(tinytuple * 2)
print(tuple[2:5])