a = "Welcome to the WOrld"
print(a)
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])
print(a[5])
print(a[6])
print(a[7])
print(a[8])
print(a[0:1])
print(a[0:2])
print(a[0:3])
print(a[0:4])
print(a[0:5])
print(a[0:6])
print(a[1:2])
print(a[0:-4])
print(a[:-1])
print(a[1:])
b = "Welcome to the  python Foundation 2021"
print(b[0])
print(b[1])
print(b[2])
print(b[3])
print(b[4])
print(b[5])
print(b[6])
print(b[7])
print(b[8])
print(b[0:1])
print(b[0:2])
print(b[0:3])
print(b[0:4])
print(b[0:5])
print(b[0:6])
print(b[1:2])
print(b[0:-4])
print(b[:-1])
print(b[1:])

#String sequence operations
 #find
print(b.find('2021'))
print(b.find('Welcome to '))
print(b.replace('p', 'P'))
#Split
#
y = 'H,e,l,l,o'
print(y.split(','))
print(b.count('1', 0, 4))
print(y.upper())
print(b.upper())
print(a.upper())
#
print(max(b))
print(min(b))
print(b.isalpha())
print(min(y))
print(max(y))
print(y.isalpha())
#
d ="Hello world"
print(d)
print(d[0:4])
print(d[2:])
print(d[:-2])
print( d * 2)
print(d + "Test")
print(type(a))
#
h ="Hello World"
print(h)
print(type(h))
print(h[0])
print(h[1])
print(h[2])
print(h[3])
print(h[4])
print(h[5])
print(h[6])
print(h[7])
print(h[8])
print(h[9])
print(h[10])
print(h[0:1])
print(h[0:2])
print(h[0:3])
print(h[0:4])
print(h[0:5])
print(h[0:6])
print(h[0:7])
print(h[0:8])
print(h[0:9])
print(h[0:10])
print(h[0:11])
print(h[1:0])
print(h[1:3])
print(h[1:5])
print(h[1:7])
print(h[1:9])
print(h[1:11])
print(h[2:0])
print(h[2:2])
print(h[2:4])
print(h[2:6])
print(h[2:8])
print(h[2:10])
# negative indexing
print(h[1:-1])
print(h[2:-1])
print(h[1:-1])
print(h[1:-2])
print(h[3:-1])
print(h[:-1])
print(h[1:])
print(h[2:])
print(dir(str))